spring:
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:127.0.0.1}:${MYSQL_PORT:3306}/${MYSQL_DATABASE:open_music}?serverTimezone=Asia/Shanghai&useUnicode=true&allowMultiQueries=true&characterEncoding=utf8&useSSL=false
    username: ${MYSQL_USER:root}
    password: ${MYSQL_PASSWORD:root1234}
system:
  init:
    # 后台系统admin账号的登录密码，每次初始化都会初始化
    password: ${SYSTEM_INIT_PASSWORD:admin}
