spring:
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:127.0.0.1}:${MYSQL_PORT:3306}/${MYSQL_DATABASE:open_music}?serverTimezone=Asia/Shanghai&useUnicode=true&allowMultiQueries=true&characterEncoding=utf8&useSSL=false
    username: ${MYSQL_USER:root}
    password: ${MYSQL_PASSWORD:root1234}
system:
  username: ${SYSTEM_USERNAME:admin}
  password: ${SYSTEM_PASSWORD:$2a$10$M.ojk5M4ZafKqkOJTeAcneh9QZXlYm2JEreeuJE0VmlEtv4fm2KHm}
music:
  link:
    # 链接来源：0-github，1-alist
    source: 1