server:
  port: 8084
  address: 0.0.0.0
  servlet:
    context-path: /

spring:
  application:
    name: woodwhales-music
  thymeleaf:
    cache: false
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  profiles:
    active: '@profiles.active@'
  sql:
    init:
      mode: always
      schema-locations: classpath:/init.sql
logging:
  level:
    org.woodwhales.music: debug
    com.baomidou: debug
music:
  link:
    # 链接来源：0-github，1-alist
    source: 1
  # 音乐网站首页
  site: "https://music.icoders.cn/"
author:
  # 作者名称
  name: "woodwhales"
  # 作者网站
  website: "https://www.woodwhales.cn"
github:
  # 是否展示 GitHub Corners
  show: true
  # github 链接
  url: "https://github.com/woodwhales/woodwhales-music"
