server:
  port: 8084
  address: 0.0.0.0
  servlet:
    context-path: /

spring:
  application:
    name: woodwhales-music
  thymeleaf:
    cache: false
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  profiles:
    active: '@profiles.active@'
logging:
  level:
    org.woodwhales.music: debug
music:
  link:
    # 链接来源：0-github，1-alist
    source: 1
